apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepfence
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://deepfence-helm-charts.s3.amazonaws.com/threatmapper
    targetRevision: 1.3.0

    chart: deepfence-console
    helm:
      parameters:
      - name: "registry.username"
        value: "mukulietllucknow"
      - name: "registry.password"
        value: "c813e95d-3bdb-4f92-99da-27641cbe3ee2"
        forceString: true 

  destination: 
    server: https://kubernetes.default.svc
    namespace: deepfence

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
