apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepfence
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mukuldeepfence/ArgoCDValidation.git
    targetRevision: HEAD
    path: helm-charts/deepfence-console

    chart: deepfence
    helm:
      parameters:
      - name: "registry.username"
        value: "mukulietllucknow"
      - name: "registry.password"
        value: "c813e95d-3bdb-4f92-99da-27641cbe3ee2"
        forceString: true 

  destination: 
    server: https://kubernetes.default.svc
    namespace: deepfence

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
