---
{{- if eq "true" .Values.registry.createRegistrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.pullSecretName }}
  labels:
    app: deepfence-console
    {{- include "deepfence-console.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---